#!/usr/bin/env bash
# show the open tab URLs from Chrome
# (adapted from https://stackoverflow.com/a/49678861/)

strings "$HOME/Library/Application Support/Google/Chrome/Default/Current Session" | grep -E '^https?://' | sort | uniq
