#!/usr/bin/env bash
# Show the open tab URLs from Chrome
# (adapted from https://stackoverflow.com/a/49678861/)

@uses-cmds strings grep sort uniq

strings "$HOME/Library/Application Support/Google/Chrome/Default/Current Session" | grep -E '^https?://' | sort | uniq
