#!/usr/bin/env bash
# Show running processes, sorted by CPU usage

@import do_cmd from .bash_shared_functions

if system_is_darwin?
then
  do_cmd top -F -R -o cpu
else
  # Linux
  do_cmd top -o +%CPU
fi
