#!/usr/bin/env bash
# Appends to a very simple did.txt file
# (adapted from https://theptrk.com/2018/07/11/did-txt-file/)

@uses_cmds vim

did_file="$HOME/Dropbox/doc/did.txt"

if [ -n "$1" ]
then
  # write the message from the command line
  timestamp="$(date +"%Y-%m-%d %H:%M:%S %A")"
  message="$1"
  echo -e "$timestamp\n- $message\n\n$(cat $did_file)" > "$did_file"
else
  # no message input, do this in vim
  # all backslashes have to be escaped because '%' in vim means current file
  vim +'r!date +"\%Y-\%m-\%d \%H:\%M:\%S \%A"' +'normal o' +'normal ggo-  ' +startinsert "$did_file"
fi

# then show what I just added to that file - print everything up to the first blank line in the file
echo ""
# don't print automatically
# once it hits a blank line quit (without printing the blank line)
# otherwise print the non-blank line
sed -n -e '/^$/ q' -e 'p' "$did_file"

