#!/usr/bin/env bash
# Appends to a very simple did.txt file
# (adapted from https://theptrk.com/2018/07/11/did-txt-file/)

@import do_cmd from .bash_shared_functions

@uses_cmds vim

did_file="$HOME/Dropbox/doc/did.txt"

# all backslashes have to be escaped because '%' in vim means current file
do_cmd vim +'r!date +"\%Y-\%m-\%d \%H:\%M:\%S \%A"' +'normal o' +'normal ggo-  ' +startinsert "$did_file"

