#!/usr/bin/env bash
# Provides a way for syntastic in vim to query the locally installed eslint version
# (from from https://github.com/vim-syntastic/syntastic/issues/2102)

@uses_cmds npx

# run eslint if it's installed globally or locally in node_modules/.bin/
# don't install eslint if it's not available (this makes vim startup super slow)
npx --no-install eslint "$@" 2>/dev/null || echo "v1.0.0"

