#!/usr/bin/env bash
# Checkout git branch from list of branches (Git Checkout from List)

@import { all_git_branches, in_git_repo, do_git } from .bash_git
@import { echo_info } from .bash_shared_functions

if in_git_repo
then
  all_branches=( $(all_git_branches | sort) )
  num_branches="${#all_branches[@]}"
  for((i=0; i<$num_branches; i++))
  do
    # display a 1-based index, which is nicer to select
    echo -e "[$(( index + 1 ))] ${all_branches[$i]}"
  done
  echo -n "Branch number: "
  read branch_num
  if [ -n "$branch_num" ] && (( "$branch_num" <= "$num_branches" ))
  then
    (( branch_index = branch_num - 1 ))
    do_git checkout "${all_branches[$branch_index]}"
  else
    echo_info "no branch selected"
  fi
fi
