#!/usr/bin/env bash
# [git] Show the current commit hash (Git CURRent)

@import { in_git_repo, do_git } from .bash_git

if in_git_repo
then
  do_git rev-parse HEAD
  do_git rev-parse --short HEAD
fi

