#!/usr/bin/env bash
# [git] Sync current branch to the upstream fork (Git Fork Sync)

@import { in_git_repo, on_symbolic_ref, current_git_branch, do_git } from .bash_git

if in_git_repo && on_symbolic_ref
then
  branch_name=$(current_git_branch)
  do_git fetch upstream && do_git merge "upstream/$branch_name" && do_git push
fi

