#!/usr/bin/env bash
# [git] Merge current branch into master (Git Merge into Master)

@import { in_git_repo, not_on_git_branch, no_uncommitted_changes, current_git_branch, do_git, gmt } from .bash_git
@import echo_err from .bash_shared_functions

if in_git_repo && not_on_git_branch 'master' && no_uncommitted_changes
then
  branch_name=$(current_git_branch)
  do_git checkout master && do_git merge "$branch_name"
  # error recovery to fix merge conflicts
  if [ "$?" -ne 0 ]
  then
    echo_err "Dang it! merge failed - good luck"
    @wait_for_keypress "Press any key to start merge resolution... "
    gmt
  fi
fi

