#!/usr/bin/env bash
# [git] Merge current branch into master (Git Merge into Master)

@import { in_git_repo, not_on_git_branch, no_uncommitted_changes, current_git_branch, do_git } from .bash_git

if in_git_repo && not_on_git_branch 'master' && no_uncommitted_changes
then
  branch_name=$(current_git_branch)
  do_git checkout master && do_git merge "$branch_name"
  # TODO: error recovery to fix merge conflicts
  # if [ "$?" -ne 0 ]; then
  #   echo_err "Dang it! merge failed - good luck"
  #   gmt
  #   read -p "Press any key to continue... " -n1 -s # DEBUG
  # fi
fi

