#!/usr/bin/env bash
# [git] Push current local branch to origin, and set upstream (Git Push Branch)

@import { in_git_repo, current_git_branch, do_git } from .bash_git

if in_git_repo
then
  branch_name=$(current_git_branch)
  do_git push -u origin "$branch_name"
fi

