#!/usr/bin/env bash
# [git] Pull changes from origin and rebase local changes (Git Pull Rebase)

@import { current_git_branch, do_git } from .bash_git

branch_name=$(current_git_branch)
# sometimes `git pull --rebase` fails with "fatal: Cannot rebase onto multiple branches."
# could try doing the full command (from https://stackoverflow.com/a/35844073)
# do_git pull origin "$branch_name" --rebase
# but sometimes that also fails,
# so be more explicit and split it into 2 commands (adapted from https://stackoverflow.com/a/35844073)
# (also prunes, which is a nice benefit)
do_git fetch --all --prune && do_git rebase "origin/$branch_name"

