#!/usr/bin/env bash
# [git] Undo the last commit (Git UNDO)

@import { in_git_repo, do_git } from .bash_git

@uses_cmds git

if in_git_repo
then
  last_commit="$(git log -1 --pretty=%B)"
  git_dir="$(git rev-parse --show-toplevel)/.git"
  do_git reset --soft HEAD~1

  # also writes the previous commit message to .git/GITGUI_MSG
  echo "$last_commit" > "$git_dir/GITGUI_MSG"
fi

