#!/usr/bin/env bash
# Create a new branch that tracks origin/master (for LinkedIn workflow)

@arg 'new_branch_name' 'Name of the new branch'

@import { do_git, in_git_repo, on_git_branch } from .bash_git

# create new branch (that tracks origin/master)
if in_git_repo && on_git_branch 'master'
then
  do_git checkout -b "$new_branch_name" origin/master
fi
