#!/usr/bin/env bash
# Clean dirs and files in a MP (for LinkedIn workflow)

# how to use this:
#  $ liclean
#  (then follow the prompts)

@import { echo_err, echo_info, do_cmd } from .bash_shared_functions

in_linkedin_mp() {
  local file_to_check="product-spec.json"
  [ -f "$file_to_check" ] && return 0 || echo_err "$(pwd) is not a LinkedIn MultiProduct (missing $file_to_check)" && return -1
}


if in_linkedin_mp; then
  username="$(whoami)"

  if [ -n "$TMPDIR" ]; then
    # $TMPDIR is set on OSX
    disk_cache_dir="$TMPDIR/$username"
  else
    # try to determine the tmpdir used by node
    # using node in the MP:
    # (have to filter out the junk printed by just)
    using_just="$(just node -e 'console.log(require("os").tmpdir())' | sed -e '/^[[:space:]]*#/ d')"
    # using system node:
    using_system="$(node -e 'console.log(require("os").tmpdir())' 2>/dev/null)"
    if [ -n "$using_just" ]; then
      disk_cache_dir="$using_just/$username"
    elif [ -n "$using_system" ]; then
      disk_cache_dir="$using_system/$username"
    else
      echo_err "could not figure out tmp directory"
    fi
  fi

  # default: remove build products and disk_cache
  echo_info "removing build files..."
  do_cmd rm -rf .eyeglass_cache/ build/ dist/ tmp/

  if [ -n "$disk_cache_dir" ]; then
    echo_info "removing disk cache files..."
    do_cmd rm -rf "$disk_cache_dir"
  fi
fi
