#!/usr/bin/env bash
# Count lines of code for the input files

@import echo_err from .bash_shared_functions

@uses-cmds sed grep

# TODO: specify to generated getopts stuff that something should be passed in
if [ "$#" -eq 0 ]
then
  echo_err "No input files given!"
  exit 1
fi

# filter out *.swp files
valid_files=( $(echo "$@" | sed -E 's/[^[:space:]]+.swp//g') )

all_files="$(cat ${valid_files[*]})"
all_files_no_blank="$(echo "$all_files" | sed '/^[[:space:]]*$/ d')"
# strips comment lines starting with '#' and '//'
all_files_no_comments="$(echo "$all_files_no_blank" | sed '/^[[:space:]]*#/ d' | sed '/^[[:space:]]*\/\// d')"

# count lines for each (from https://stackoverflow.com/a/42399738)
num_lines="$(echo -n "$all_files" | grep -c '^' )"
num_lines_no_blank="$(echo -n "$all_files_no_blank" | grep -c '^' )"
num_lines_no_comments="$(echo -n "$all_files_no_comments" | grep -c '^' )"

echo "Files          : ${#valid_files[@]}"
echo "Total lines    : $num_lines"
echo "No empty lines : $num_lines_no_blank"
echo "No comments    : $num_lines_no_comments"

