#!/usr/bin/env bash
# create a new RB from the local changes, or update existing review

# TODO - blurb about how to use this

@import echo_err from .bash_shared_functions
@import echo_ack from .bash_shared_functions
@import echo_info from .bash_shared_functions

@import do_git from .bash_git
@import git_review_board_id from .bash_git
@import current_git_branch from .bash_git

@uses_cmds jq expect git

# SETTINGS
ADDITIONAL_USERS_GROUPS="flagship-productivity-reviewers"  # (comma-delimited)

branch_name=$(current_git_branch)
review_id="$(git_review_board_id $branch_name)"

# check if there is already a RB for this branch
if [ -n "$review_id" ]
then
  # update

  # TODO: check if ACL is covered, then do platform-review if that is required?
  # see go/voyager/web/platform-review for details of that command

  echo_info "RB $review_id already exists for this branch - updating..."
  # if there is an argument supplied, use that for the description
  input_description="$1"
  echo -n "Description of these changes [$input_description]: "
  read diff_description
  if [ -z "$diff_description" ]
  then
    diff_description="$input_description"
  fi
  do_git review update --open --diff-description "$diff_description"
  # use `git review update --help` to figure out how to add other options
else
  # create

  echo_info "No RB for this branch - creating one..."
  # if there is an argument supplied, use that for the description
  if [ -n "$1" ]
  then
    input_description="$1"
  else
    # otherwise use the commit message
    input_description="$(git log -1 --pretty=%B)"
  fi
  echo -n "Description of these changes [$input_description]: "
  read rb_description
  if [ -z "$rb_description" ]
  then
    rb_description="$input_description"
  fi

  # TODO: prompt for more things, with defaults?

  # because do_git function does not work inside spawn, just echo that here
  echo_ack "( git review create --owners-only --open --description '$rb_description' )"
  # use `expect` to automatically answer the prompts, which look like this:
  expect <<EndOfGitReviewExpect
    set timeout 60
    spawn git review create --owners-only --open --description "$rb_description"
    # regex matches across newlines
    expect -re "^Recommended reviewers.*Additional reviewers.*"
    send "$ADDITIONAL_USERS_GROUPS\n"
    # allow command to run to completion
    expect eof
EndOfGitReviewExpect
  # use `git review create --help` to figure out how to add other options
fi

