#!/usr/bin/env bash
# pastes template into Description field when creating a new Jira ticket

@import echo_info from .bash_shared_functions

@uses_cmds osascript

join() {
  local IFS="/"
  echo "$*"
}

TICKET_TASK="task"
TICKET_BUG="bug"
TICKET_RESEARCH="research"

ticket_types=( $TICKET_TASK $TICKET_BUG $TICKET_RESEARCH )
default_type="$TICKET_TASK"

echo -n "Ticket type - $(join ${ticket_types[@]}) [$default_type]: "
read input_type
if [ -z "$input_type" ]
then
  ticket_type="$default_type"
else
  ticket_type="$input_type"
fi

# make sure Chrome window has focus
osascript -e 'tell application "Google Chrome" to activate'

# emulate keystrokes to type the template into the field
# TODO: allow typing in a partial name as long as it is enough to ID the task
if [ "$ticket_type" == "$TICKET_TASK" ]
then
  echo_info "Filling out ticket type '$TICKET_TASK'"
  osascript <<EOFTask
tell application "System Events"
  keystroke "h2. Summary" & return & return
  keystroke "h2. Objective" & return & return
  keystroke "h2. Acceptance Criteria" & return & return
  keystroke "h2. Pre-Requisites" & return & return
end tell
EOFTask
elif [ "$ticket_type" == "$TICKET_BUG" ]
then
  echo_info "Filling out ticket type '$TICKET_BUG'"
  osascript <<EOFBug
tell application "System Events"
  keystroke "h2. Summary" & return & return
  keystroke "h2. Steps to Reproduce" & return & return
  keystroke "h2. Bug Fix Acceptance Criteria" & return & return
  keystroke "h2. Additional Details" & return & return
end tell
EOFBug
elif [ "$ticket_type" == "$TICKET_RESEARCH" ]
then
  echo_info "Filling out ticket type '$TICKET_RESEARCH'"
  osascript <<EOFResearch
tell application "System Events"
  keystroke "h2. Summary" & return & return
  keystroke "h2. Objective" & return & return
  keystroke "h2. Components" & return & return
  keystroke "h2. Contacts" & return & return
end tell
EOFResearch
fi
