#!/usr/bin/env bash
# send email from API email address, using SMTP

to_email="${1:?First arg is the to: email address}"
subject="${2:?Second arg is the subject}"
message="${3:?Third arg is the message}"

GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
user="$($GET_API_TOKEN email-api-user)"
pass="$($GET_API_TOKEN email-api-pass)"

server="smtp.gmail.com:587"

# from http://caspian.dotconf.net/menu/Software/SendEmail/
# install with `brew install sendemail` or `yum install sendemail`
SEND_EMAIL="$( \
  ([ -f /usr/local/bin/sendEmail ] && echo '/usr/local/bin/sendEmail') \
  || ([ -f /usr/bin/sendEmail ] && echo '/usr/bin/sendEmail') \
  || echo 'sendEmail' \
)"

$SEND_EMAIL -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"

