#!/usr/bin/env bash
# send email from main email address, using SMTP

@uses_cmds sendEmail

to_email="${1:?First arg is the to: email address}"
subject="${2:?Second arg is the subject}"
message="${3:?Third arg is the message}"

GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
user="$($GET_API_TOKEN email-main-user)"
pass="$($GET_API_TOKEN email-main-pass)"

server="smtp.gmail.com:587"

# from http://caspian.dotconf.net/menu/Software/SendEmail/
# install with `brew install sendemail` or `yum install sendemail`

sendEmail -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"

