#!/usr/bin/env bash
# Send email from outlook address, using SMTP

@arg 'to_email' 'Address to send the email to'
@arg 'subject' 'Email subject line'
@arg 'message' 'Email message contents'

@uses-cmds sendEmail

GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
from_addr="$($GET_API_TOKEN outlook-email)"
user="$($GET_API_TOKEN outlook-user)"
pass="$($GET_API_TOKEN outlook-pass)"

outlook_smtp='smtp-mail.outlook.com:587'

# from http://caspian.dotconf.net/menu/Software/SendEmail/
# install with `brew install sendemail` or `yum install sendemail`

sendEmail -o tls=yes -f "$from_addr" -t "$to_email" -s "$outlook_smtp" -xu "$user" -xp "$pass" -u "$subject" -m "$email_contents"

