#!/usr/bin/env bash
# Send email from main email address, using SMTP

@arg 'to_email' 'Address to send the email to'
@arg 'subject' 'Email subject line'
@arg 'message' 'Email message contents'

@uses-cmds sendEmail

GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
user="$($GET_API_TOKEN email-main-user)"
pass="$($GET_API_TOKEN email-main-pass)"

server="smtp.gmail.com:587"

# from http://caspian.dotconf.net/menu/Software/SendEmail/
# install with `brew install sendemail` or `yum install sendemail`

sendEmail -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"

