#!/usr/bin/env bash
# Send email from API email address, using SMTP

@arg 'to_email' 'Address to send the email to'
@arg 'subject' 'Email subject line'
@arg 'message' 'Email message contents'

@uses_cmds sendEmail

GET_API_TOKEN="$HOME/Dropbox/secret/get-api-token"
user="$($GET_API_TOKEN email-api-user)"
pass="$($GET_API_TOKEN email-api-pass)"

server="smtp.gmail.com:587"

# from http://caspian.dotconf.net/menu/Software/SendEmail/
# install with `brew install sendemail` or `yum install sendemail`

sendEmail -o tls=yes -f "$user" -t "$to_email" -s "$server" -xu "$user" -xp "$pass" -u "$subject" -m "$message"

