#!/usr/bin/env bash
# Serve the files in the current directory
# (from https://stackoverflow.com/a/7105609)

@arg_optional 'port' 'The port to serve from' '8080'

@import_var { COLOR_RESET, COLOR_FG_BOLD_BLUE } from .bash_colors

@uses_cmds ifconfig awk ruby

address="$(ifconfig | awk '/inet / && $2 != "127.0.0.1"{print $2}')"
echo -e "Current directory: ${COLOR_FG_BOLD_BLUE}$PWD${COLOR_RESET}"
echo -e "Serving at ${COLOR_FG_BOLD_BLUE}$address:$port${COLOR_RESET}"
ruby -run -e httpd . -p $port

