#!/usr/bin/env bash
# Show a busy spinner while the input PID is running

# use this like:
#  $ sleep 10 &
#  $ spinner $!
#  ⠼

# or you can add an optional message for the spinner
#  $ spinner -m "grepping files..." $!
#  ⠼ grepping files...

@arg_optional 'm:' 'spin_msg' 'Text to display along with the spinner animation'
@arg 'cmd_pid' 'PID of the long-running command'

spin_chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' # braille dots

num_chars=${#spin_chars}
total_length=$(( 2 + ${#spin_msg} ))

i=0
while kill -0 $cmd_pid 2>/dev/null
do
  i=$(( (i + 1) % num_chars ))
  printf "\r${spin_chars:$i:1} ${spin_msg}" >&2
  sleep 0.1
done

# attempt to clean up (doesn't always work)
printf "\r%-${total_length}s\r" ' ' >&2

