#!/usr/bin/env bash
# show a busy spinner while the input PID is running

# use this like:
#  $ sleep 10 &
#  $ spinner $!
#  ⠼

# arguments:
cmd_pid="${1:?must specify pid for spinner}"

spin_chars='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏' # braille dots
# spin_chars='-\|/' # more basic option

num_chars=${#spin_chars}

i=0
while kill -0 $cmd_pid 2>/dev/null
do
  i=$(( (i + 1) % num_chars ))
  printf "\b${spin_chars:$i:1}" >&2
  sleep 0.1
done

# attempt to clean up (doesn't always work)
printf "\b" >&2

