#!/usr/bin/env bash
# [git] Squash the input number of commits on the current branch

@arg 'num_commits' 'Number of commits to squash'
@arg 'commit_msg' 'Commit message'
@arg_optional 'commit_msg_extra_line' 'Extra line for more info, overrides, etc.'

@uses_funcs do_git

# "squashes" commits by combining them into a single commit
if [ -n "$commit_msg_extra_line" ]; then
  # multiple lines of commit messages
  do_git reset --soft HEAD~$num_commits && do_git commit -m "$commit_msg" -m "$commit_msg_extra_line"
else
  do_git reset --soft HEAD~$num_commits && do_git commit -m "$commit_msg"
fi

