#!/usr/bin/env bash
# Open the browser with info on the input stock

@arg 'stock_symbol' 'The symbol to use to look up the stock'

@uses-cmds open/Darwin xdg-open/Linux

stock_url="https://finance.yahoo.com/quote/$stock_symbol/"

if @system_is_linux?
then
  xdg-open "$stock_url"
elif @system_is_darwin?
then
  open "$stock_url"
fi

