#!/usr/bin/env bash
# Open the browser with info on the input stock

@arg 'stock_symbol' 'The symbol to use to look up the stock'

@uses_cmds open/OSX xdg-open/Linux

stock_url="https://finance.yahoo.com/quote/$stock_symbol/"

if ?PLATFORM_IS_LINUX?
then
  xdg-open "$stock_url"
elif ?PLATFORM_IS_MAC?
then
  open "$stock_url"
fi

