#!/usr/bin/env bash
# Show any TODOs from comments in source code

# TODO: need a way to specify "all remaining args", so I can grep multiple dirs
@arg_optional 'in_dir' 'Directory to grep for TODOs in' '.'

@import_var { COLOR_RESET, COLOR_FG_BOLD_BLUE } from .bash_colors

@uses_cmds grep wc tr spinner

# possible comment styles
hash_comments='#'         # Python, Bash, Ruby, Perl
slash_comments='//'       # C/C++, Javascript, Java, PHP
dquote_comments='"'       # vim script
html_comments='<!--'      # HTML, XML
slash_block_comments='/*' # C/C++, CSS, Java
dash_comments='--'        # SQL
no_comments=''            # not in a comment (for markdown and some other files)

# use process substitution to capture the output asynchronously
# (from https://stackoverflow.com/a/20018118/)
exec 3< <(grep \
  -nrIF \
  --color=always \
  --exclude-dir bower_components \
  --exclude-dir node_modules \
  --exclude-dir target \
  --exclude-dir .git \
  --exclude-dir .vim \
  -e "$hash_comments TODO" \
  -e "$slash_comments TODO" \
  -e "$dquote_comments TODO" \
  -e "$html_comments TODO" \
  -e "$slash_block_comments TODO" \
  -e "$dash_comments TODO" \
  -e "${no_comments}TODO:" \
  "$in_dir" \
  2>/dev/null \
)
spinner -m "grepping files..." $!

matched_lines="$(cat <&3)"
# if grep output is empty it will still count as one line (because of echo), so avoid that
if [ -n "$matched_lines" ]
then
  num_lines="$(echo "$matched_lines" | wc -l | tr -d '[:space:]')"
else
  num_lines=0
fi

echo "$matched_lines"
echo -e "${COLOR_FG_BOLD_BLUE}total: $num_lines${COLOR_RESET}"

