#!/usr/bin/env bash
# Show any TODOs from comments in source code

@arg_optional 'in_dir' 'Directory to grep for TODOs in (defaults to current dir)'

@import_var { COLOR_RESET, COLOR_FG_BOLD_BLUE } from .bash_colors

@uses_cmds grep wc tr spinner

in_dir="${in_dir:-.}" # default to current directory

# possible comment styles
hash_comments='#'         # Python, Bash, Ruby, Perl
slash_comments='//'       # C/C++, Javascript, Java, PHP
dquote_comments='"'       # vim script
html_comments='<!--'      # HTML, XML
slash_block_comments='/*' # C/C++, CSS, Java
dash_comments='--'        # SQL

# use process substitution to capture the output asynchronously
# (from https://stackoverflow.com/a/20018118/)
exec 3< <(grep \
  -nrIF \
  --color=always \
  --exclude-dir bower_components \
  --exclude-dir node_modules \
  --exclude-dir target \
  --exclude-dir .git \
  --exclude-dir .vim \
  -e "$hash_comments TODO" \
  -e "$slash_comments TODO" \
  -e "$dquote_comments TODO" \
  -e "$html_comments TODO" \
  -e "$slash_block_comments TODO" \
  -e "$dash_comments TODO" \
  "$in_dir" \
  2>/dev/null \
)
spinner -m "grepping files..." $!

matched_lines="$(cat <&3)"

num_lines="$(echo "$matched_lines" | wc -l | tr -d '[:space:]')"

echo "$matched_lines"
echo -e "${COLOR_FG_BOLD_BLUE}total: $num_lines${COLOR_RESET}"

