#!/usr/bin/env bash
# Verify the links to the dotfiles haven't changed

@arg_optional 'checkout_dir' 'The directory where the repo is checked out' '$HOME/dotfiles'

@import echo_err from .bash_shared_functions

@uses_cmds readlink

# use bash 4.x associative arrays
declare -A links

# vim
links[".vimrc"]=".vimrc"
links[".vim"]=".vim"

# bash
links[".bash_profile"]=".bash_profile"
links[".bashrc"]=".bashrc"

# inputrc
links[".inputrc"]=".inputrc"

# gitignore
links[".gitignore"]=".gitignore"

# tmux
links[".tmux.conf"]=".tmux.conf"

# bundler
links[".bundle"]=".bundle"

# rubocop
links[".rubocop.yml"]=".rubocop.yml"

# platform-specific
if system_is_darwin?
then
  # ssh
  links[".ssh/config"]=".ssh-config-mac"
elif system_is_linux?
then
  # ssh
  links[".ssh/config"]=".ssh-config-linux"
fi

# verify the links
for i in "${!links[@]}"
do
  if [ -L "$HOME/$i" ]
  then
    # symlink exists, check if it points to the right place
    link_target="$(readlink $HOME/$i)"
    if [ "$link_target" != "$checkout_dir/${links[$i]}" ]
    then
      echo_err "symlink '$HOME/$i => $checkout_dir/${links[$i]}' has been changed!"
    fi
  else
    echo_err "symlink '$HOME/$i => $checkout_dir/${links[$i]}' does not exist!"
  fi
done

