#!/usr/bin/env bash
# get current weather by zip code
# using OpenWeatherMap API - http://openweathermap.org/api

@import_var { COLOR_RESET, COLOR_FG_BOLD_BLUE } from .bash_colors

@uses_cmds curl jq bc xargs

# Daly City, Mountain View, SF
zip_codes=( 94015 94043 94105 )

for zip in ${zip_codes[*]}; do
  api_key="$($HOME/Dropbox/secret/get-api-token open-weather-map)"
  page=$(curl "http://api.openweathermap.org/data/2.5/weather?zip=${zip},us&appid=${api_key}" 2>/dev/null)
  name="$(echo $page | jq --raw-output -M '.name')"
  temp_kelvin="$(echo $page | jq --raw-output -M '.main.temp')"
  temp_celcius=$(echo "$temp_kelvin - 273.15" | bc -q | xargs printf "%.1f") # convert to C and format
  temp_f=$(echo "(1.8 * ($temp_kelvin - 273.15)) + 32" | bc -q | xargs printf "%.1f") # convert to F and format
  humidity="$(echo $page | jq --raw-output -M '.main.humidity')"
  main="$(echo $page | jq --raw-output -M '.weather | .[0] | .main')"
  description="$(echo $page | jq --raw-output -M '.weather | .[0] | .description')"

  echo -e "${COLOR_FG_BOLD_BLUE}$name${COLOR_RESET} ($zip)"
  echo -e "Weather:     ${COLOR_FG_BOLD_BLUE}$main - $description${COLOR_RESET}"
  echo -e "Temperature: ${COLOR_FG_BOLD_BLUE}$temp_f${COLOR_RESET}°F (${temp_celcius}°C)"
  echo -e "Humidity:    ${COLOR_FG_BOLD_BLUE}$humidity${COLOR_RESET}%"
  echo ""
done

