#!/usr/bin/env bash

@uses_cmds gdate sed

yesterday_date="$(gdate -d '1 day ago' +"%Y-%m-%d")"
echo "Items from yesterday, $yesterday_date:"

did_file="$HOME/Dropbox/doc/did.txt"

# print all the entries matching yesterday's date
# (from http://www.grymoire.com/Unix/Sed.html#toc-uh-58)
sed -n '
  # if an empty line, check the paragraph
  /^$/ b para
  # else add it to the hold buffer
  H
  # at end of file, check paragraph
  $ b para
  # now branch to end of script
  b
  # this is where a paragraph is checked for the pattern
  :para
  # return the entire paragraph
  # into the pattern space
  x
  # look for the pattern, if there - print
  /'$yesterday_date'/ p
' "$did_file"

