#!/usr/bin/env bash
# Close the current desktop (Space) with Mission Control
# (modified from the new-desktop script)

# NOTE: enable reduced motion so the animations have less affect on the timing
# System Preferences > Accessibility > Display > Reduce Motion [✓]

########################################
# figure out desktop and resolution info
########################################

# NOTE: when this is run via Karabiner, the `jq` command cannot be found, so I'm using the full path here

# the spaces info, as JSON
spaces_json="$(plutil -convert json -o - "$HOME/Library/Preferences/com.apple.spaces.plist")"

# find the .Monitors section with ."Display Identifier" == "Main", and count the number of spaces
total_desktops="$(echo "$spaces_json" | /usr/local/bin/jq '.SpacesDisplayConfiguration."Management Data".Monitors[] | if ."Display Identifier" == "Main" then .Spaces else empty end | length')"

echo "Currently, there are $total_desktops desktops"

# for debugging:
#echo "$spaces_json" | /usr/local/bin/jq -r '.SpacesDisplayConfiguration."Management Data".Monitors[]'

# get .id of ."Current Space"
# (using id64 because uuid is blank for the first space)
current_id="$(echo "$spaces_json" | /usr/local/bin/jq -r '.SpacesDisplayConfiguration."Management Data".Monitors[] | if ."Current Space" then ."Current Space".id64 else empty end')"

echo "Desktop ID = $current_id"

# use that to find the desktop number
# (NOT using base64 idea from https://starkandwayne.com/blog/bash-for-loop-over-json-array-using-jq/ anymore)

# output one ID each line for the .Spaces where ."Display Identifier" == "Main",
space_ids="$(echo "$spaces_json" | /usr/local/bin/jq -r '.SpacesDisplayConfiguration."Management Data".Monitors[] | if ."Display Identifier" == "Main" then .Spaces[] else empty end | .id64')"

# loop over that, to find the index matching our current ID
index=0
for id in $space_ids; do
  if [ "$id" == "$current_id" ]
  then
    current_index="$index"
    break
  fi
  index=$(( index + 1 ))
done

echo "Desktop index = $current_index"

# get the current resolution

# trying the answers on https://superuser.com/q/447295
#
# wrong:
# $ system_profiler SPDisplaysDataType | grep Resolution
#           Resolution: 2880 x 1800 Retina
#
# right:
# $ osascript -e 'tell application "Finder" to get bounds of window of desktop'
# 0, 0, 1680, 1050

resolution_info="$(osascript -e 'tell application "Finder" to get bounds of window of desktop' | tr -d ',')"
display_width="$(echo "$resolution_info" | awk '{print $3}' )"
display_height="$(echo "$resolution_info" | awk '{print $4}' )"

echo "Display resolution: $display_width x $display_height"

########################################
# get into Mission Control
########################################

echo "opening Mission Control..."

# run the app directly
# (in 10.15 Catalina this moved to /System)
MC_PATH="/Applications/Mission Control.app/Contents/MacOS/Mission Control"
MC_PATH_CATALINA="/System/Applications/Mission Control.app/Contents/MacOS/Mission Control"

if [ -f "$MC_PATH" ]; then
  "$MC_PATH"
elif [ -f "$MC_PATH_CATALINA" ]; then
  "$MC_PATH_CATALINA"
fi

# give that time to animate
sleep 0.5

########################################
# close the current desktop
########################################

# ideas for how to figure out the button to click on:
#   https://www.reddit.com/r/applescript/comments/360l6v/close_a_space_with_applescript/cr9tj4j/
#   https://superuser.com/a/336553

# let's figure this out...


# echo "elements in Dock:"
# osascript <<END_SCRIPT
# tell application "System Events"
#     UI elements of process "Dock"
# end tell
# END_SCRIPT
#
# which returns:
#  elements in Dock:
#  list 1 of application process Dock, group Mission Control of application process Dock
#
# ok, so going to use Mission Control


# echo "elements in Mission Control:"
# osascript <<END_SCRIPT
# tell application "System Events"
#     UI elements of (group "Mission Control" of process "Dock")
# end tell
# END_SCRIPT
#
# returns:
#  elements in Mission Control:
#  group 1 of group Mission Control of application process Dock, group 2 of group Mission Control of application process Dock
#
# hmm, group 1 and group 2, let's see what's in each one


# echo "elements in group 1:"
# osascript <<END_SCRIPT
# tell application "System Events"
#    UI elements of (group 1 of group "Mission Control" of process "Dock")
# end tell
# END_SCRIPT
#
# echo "elements in group 2:"
# osascript <<END_SCRIPT
# tell application "System Events"
#    UI elements of (group 2 of group "Mission Control" of process "Dock")
# end tell
# END_SCRIPT
#
# returns:
#  elements in group 1:
#  group 1 of group 1 of group Mission Control of application process Dock, group Spaces Bar of group 1 of group Mission Control of application process Dock
#  elements in group 2:
#  group 1 of group 2 of group Mission Control of application process Dock, group Spaces Bar of group 2 of group Mission Control of application process Dock
#
# looks like the same thing in each, maybe because I have an external monitor hooked up, there's one for each monitor?
# (turn off monitor)
#
#  elements in group 1:
#  group 1 of group 1 of group Mission Control of application process Dock, group Spaces Bar of group 1 of group Mission Control of application process Dock
#  elements in group 2:
#  36:47: execution error: System Events got an error: Can’t get group 2 of group "Mission Control" of process "Dock". Invalid index. (-1719)
#
# yup, so group 1 is my main monitor, which is what I want
# and I want the Spaces Bar (group 1 is the open windows in the bottom pane)


# echo "elements in spaces bar:"
# osascript <<END_SCRIPT
# tell application "System Events"
#    UI elements of (group "Spaces Bar" of group 1 of group "Mission Control" of process "Dock")
# end tell
# END_SCRIPT

# returns:
#  elements in spaces bar:
#  list 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock, button 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock
#
# I already know that button 1 is the button to add a new desktop (from the new-desktop script),
# so we must want list 1, which I'm guessing is the list of desktops


# echo "elements in list:"
# osascript <<END_SCRIPT
# tell application "System Events"
#    UI elements of (list 1 of group "Spaces Bar" of group 1 of group "Mission Control" of process "Dock")
# end tell
# END_SCRIPT
#
# returns:
#  elements in list:
#  button Desktop 1 of list 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock, button Desktop 2 of list 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock, button Desktop 3 of list 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock, button Desktop 4 of list 1 of group Spaces Bar of group 1 of group Mission Control of application process Dock
#
# just buttons to choose a desktop, because mission control is not expanded, hmm...


# ok, so that seems to be a dead end - there is no button that is part of the UI, that I can figure out how to get to



# just do this with mouse movements
# using cliclick (https://github.com/BlueM/cliclick)
# (same as jq, have to give full path for things in /usr/loca/bin/)

# move to the top of the screen to expand mission control
echo "moving mouse to expand Mission Control..."
/usr/local/bin/cliclick m:100,0

sleep 0.5

# close button locations - right now this only works for 1680x1050
button_x=$(( 856 - (total_desktops * 88) + (current_index * 176) ))
button_y=28

echo "Clicking close button for desktop $current_index, at $button_x,$button_y"

# hold option down
#osascript -e 'tell application "System Events" to key down option'

# wait for the close buttons to appear
#sleep 0.5

# click the close button
/usr/local/bin/cliclick "m:$button_x,$button_y"
#cliclick "c:$button_x,$button_y"

# option up
#osascript -e 'tell application "System Events" to key up option'

exit

########################################
# get out of Mission Control
########################################

# then escape to get out of mission control
osascript -e 'tell application "System Events" to key code 53'

