#!/usr/bin/env bash

# Set the "Do Not Disturb" feature in OSX, for a limited amount of time
# (normally you set it and it's on until midnight, which is not great)

# from:
# https://apple.stackexchange.com/a/303400
# https://heyfocus.com/blog/enabling-do-not-disturb-mode/

# input the number of minutes to sleep
echo -n "DND for how many minutes? [default 30] "
read sleep_minutes
if [ -z "$sleep_minutes" ]
then
  sleep_minutes=30
fi
# and get seconds for the sleep command
sleep_seconds=$(( sleep_minutes * 60 ))

# set DND
defaults -currentHost write ~/Library/Preferences/ByHost/com.apple.notificationcenterui doNotDisturb -boolean true
defaults -currentHost write ~/Library/Preferences/ByHost/com.apple.notificationcenterui doNotDisturbDate -date "$(date -u +"%Y-%m-%d %H:%M:%S +0000")"
killall NotificationCenter
echo "Turned DND on"

echo "Sleeping for $sleep_minutes minutes..."
#sleep $sleep_seconds
sleep 5

# clear DND
defaults -currentHost write ~/Library/Preferences/ByHost/com.apple.notificationcenterui doNotDisturb -boolean false
killall NotificationCenter
echo "Turned DND off"

# and send a notification, now that can see them again
sound_name="Glass" # see /System/Library/Sounds/ for list of sounds
title="Notifications are re-enabled"
message="Do Not Disturb was on for $sleep_minutes minutes"

# use terminal-notifier instead of osascript (see https://github.com/julienXX/terminal-notifier)
# so that I don't have to re-quote everything
terminal-notifier -message "$message" -title "$title" -sound "$sound_name"
