#!/usr/bin/env bash
# Opens new iTerm2 window, and runs "good-morning" command

# check if iterm2 is running - if not, we need to start it
pgrep -a iTerm2
if [ "$?" -eq 0 ]
then
  # iTerm2 alread running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

# change directory into dotfiles
# pull and rebase to pick up recent changes
# then run the script
osascript <<EOF
tell application "System Events"
  keystroke "cd src/gh/dotfiles/" & return
  delay 0.5
  keystroke "gpr" & return
  delay 5
  keystroke "good-morning" & return
end tell
EOF
