#!/usr/bin/env bash
# Opens new iTerm2 window, and runs "good-morning" command

# check if iterm2 is running - if not, we need to start it
pgrep -a iTerm2
if [ "$?" -eq 0 ]
then
  # iTerm2 alread running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

# resize the terminal to 108W x 44H chars (so the Listr tasks fit without scrolling)
# change directory into dotfiles
# pull and rebase to pick up recent changes, then run the script
osascript <<EOF
tell application "System Events"
  keystroke "printf '\\\\033[8;44;108t'; cd src/gh/dotfiles/; gpr; yi; good-morning" & return
end tell
EOF
