#!/usr/bin/env bash
# formats the interview feedback nicely for hirein

# this is a good reference for using osascript:
# https://eastmanreference.com/how-to-automate-your-keyboard-in-mac-os-x-with-applescript

# make sure Chrome window has focus
osascript -e 'tell application "Google Chrome" to activate'

echo "Populating interview feedback text..."

# emulate keystrokes to type the formatted text into the field
  osascript <<EOF
tell application "System Events"
  keystroke "b" using command down
  keystroke "Intros and Resume"
  keystroke "b" using command down
  keystroke ": X minutes" & return
  keystroke "TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Brace Matching (link in notes)"
  keystroke "b" using command down
  keystroke ": X minutes" & return
  keystroke "TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Max Contiguous Subsequence"
  keystroke "b" using command down
  keystroke ": X minutes" & return
  keystroke "TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Function Time (link in notes)"
  keystroke "b" using command down
  keystroke ": X minutes" & return
  keystroke "TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Good"
  keystroke "b" using command down
  keystroke ":" & return
  keystroke "- TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Fair"
  keystroke "b" using command down
  keystroke ":" & return
  keystroke "- TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Poor"
  keystroke "b" using command down
  keystroke ":" & return
  keystroke "- TODO" & return
  delay 0.2

  keystroke "b" using command down
  keystroke "Overall"
  keystroke "b" using command down
  keystroke ":" & return
  keystroke "TODO"
end tell
EOF
