#!/usr/bin/env bash
# Opens new iTerm2 window, and runs "keyboard-shortcut-help" command

# check if iterm2 is running - if not, we need to start it
if pgrep -a iTerm2
then
  # iTerm2 already running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

# run the script
osascript <<EOF
tell application "System Events"
  keystroke "echo ''; keyboard-shortcut-help; echo ''; echo 'Press any key to exit...'; read -n1 -s; exit" & return
end tell
EOF
