#!/usr/bin/env bash
# Kill a bunch of things to reset at the beginning of the day, or whenever

# All of these use -I, which asks for confirmation before killing

COLOR_FG_BOLD_BLUE='\033[1;34m'
COLOR_RESET='\033[0m'

# echo with blue text
echo_info() {
  echo -e "${COLOR_FG_BOLD_BLUE}$@${COLOR_RESET}"
}


# close the Cisco AnyConnect VPN client, if I had that running at home
echo_info "Cisco VPN"
pkill -I AnyConnect || echo "(no process found)"

# close Outlook, so I can restart it to pick up any new stuff
# (this will bring up a dialog about force quitting, whatever I just want to close you dumb program)
echo_info "Outlook"
pkill -I Outlook || echo "(no process found)"

# close Slack, to reclaim memory and reset its state
echo_info "Slack"
pkill -I Slack || echo "(no process found)"

# same with Discord
echo_info "Discord"
pkill -I Discord || echo "(no process found)"

# in case I left this open
echo_info "KeePassX"
pkill -I KeePassX || echo "(no process found)"

# any images, PDFs, etc. that are still open
echo_info "Preview"
pkill -I Preview || echo "(no process found)"
