#!/usr/bin/env bash
# Auto-kill a bunch of things to reset at the beginning of the day, or whenever

##############################
# let the killing begin
##############################

# close the Cisco AnyConnect VPN client, if I had that running at home
kill-proc-name "AnyConnect"

# close Outlook, so I can restart it to pick up any new stuff
kill-proc-name "Outlook"
# if successful, that will bring up a dialog about force quitting, whatever, don't care, kill that too
sleep 0.5
kill-proc-name "Microsoft Error Reporting"

# close Slack, to reclaim memory and reset its state
kill-proc-name "Slack"

# same with Discord
kill-proc-name "Discord"

# in case I left this open
kill-proc-name "KeePassX"

# any images, PDFs, etc. that are still open
kill-proc-name "Preview"

# if I left Cisco Proximity running
# (lower case b/c the proc name is that way)
kill-proc-name "proximity"

# if I left VLC running after listening to music
kill-proc-name "VLC"
