#!/usr/bin/env bash
# Auto-kill a bunch of things to reset at the beginning of the day, or whenever

# colors
COLOR_RESET='\033[0m'
COLOR_FG_BOLD_GREEN='\033[1;32m'
COLOR_FG_GREEN='\033[0;32m'
COLOR_FG_RED='\033[0;31m'

# helper functions
proc-kill-info() {
  action="$1"
  details="$2"

  echo -e -n " ${COLOR_FG_BOLD_GREEN}$action${COLOR_RESET} $details..."
}
proc-killed() {
  echo -e "[${COLOR_FG_GREEN}OK${COLOR_RESET}]"
}
proc-not-found() {
  echo -e "(${COLOR_FG_RED}not found${COLOR_RESET})"
}
kill-proc-name() {
  proc_name="$1"

  proc-kill-info "kill" "'$proc_name'"
  pkill "$proc_name" && proc-killed || proc-not-found
}


##############################
# let the killing begin
##############################

# close the Cisco AnyConnect VPN client, if I had that running at home
kill-proc-name "AnyConnect"

# close Outlook, so I can restart it to pick up any new stuff
kill-proc-name "Outlook"
# if successful, that will bring up a dialog about force quitting, whatever, don't care, kill that too
sleep 0.5
kill-proc-name "Microsoft Error Reporting"

# close Slack, to reclaim memory and reset its state
kill-proc-name "Slack"

# same with Discord
kill-proc-name "Discord"

# in case I left this open
kill-proc-name "KeePassX"

# any images, PDFs, etc. that are still open
kill-proc-name "Preview"

# if I left Cisco Proximity running
# (lower case b/c the proc name is that way)
kill-proc-name "proximity"

# if I left VLC running after listening to music
kill-proc-name "VLC"
