#!/usr/bin/env bash

COLOR_FG_BOLD_BLUE='\033[1;34m'
COLOR_FG_GREEN='\033[0;32m'
COLOR_FG_RED='\033[0;31m'
COLOR_FG_YELLOW='\033[0;33m'
COLOR_RESET='\033[0m'

echo_err ()
{
    echo -e "${COLOR_FG_RED}$@${COLOR_RESET}" 1>&2
}

show_help_msg() {
  echo "make-dotfile-links - Create links for dotfiles"
  echo 'Usage: make-dotfile-links [options] [checkout_dir]'
  echo ''
  echo 'Options:'
  echo '  -h               Show this help message'
  echo ''
  echo 'Arguments:'
  echo '  checkout_dir     (optional) The directory where the repo is checked out (defaults to "$HOME/dotfiles")'
}

while getopts ":h" opt
do
  case $opt in
    h)
      show_help_msg && exit 0
      ;;
    \?)
      echo_err "$0: invalid option '-$OPTARG'"
      exit 1
      ;;
    :)
      echo_err "$0: option '-$OPTARG' requires an argument"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# optional arg of where the repo is checked out
checkout_dir="${1:-$HOME/src/gh/dotfiles}"

# use bash 4.x associative arrays
declare -A links

# vim
links[".vimrc"]=".vimrc"
links[".vim"]=".vim"

# bash
links[".bash_profile"]=".bash_profile"
links[".bashrc"]=".bashrc"

# inputrc
links[".inputrc"]=".inputrc"

# git
links[".gitignore"]=".gitignore"
links[".gitconfig"]=".gitconfig"
links[".gitconfig-oss"]=".gitconfig-oss"
links[".gitconfig-work"]=".gitconfig-work"

# tmux
links[".tmux.conf"]=".tmux.conf"

# bundler
links[".bundle"]=".bundle"

# rubocop
links[".rubocop.yml"]=".rubocop.yml"

# karabiner elements
links[".config/karabiner"]="karabiner"

# typescript
links["tsconfig.json"]="tsconfig.json"

# eslint
links[".eslintrc.js"]=".eslintrc.js"


# machine-specific
host_name="$(hostname)"
if [[ "$host_name" =~ (MacBook-Air|Michaels-Air) ]]
then
  # home laptop
  links[".ssh/config"]=".ssh-config-mac"
elif [[ "$host_name" =~ mistewar-mn ]]
then
  # work laptop
  links[".ssh/config.custom"]=".ssh-config-mac"
elif [[ "$host_name" =~ mistewar-ld ]]
then
  # work vm
  links[".ssh/config.custom"]=".ssh-config-linux"
else
  echo_err "Machine '$host_name' has not been configured for this script"
  exit 1
fi

# create the links
for i in "${!links[@]}"
do
  echo -n "$HOME/$i => $checkout_dir/${links[$i]}"

  if [ -L "$HOME/$i" ]
  then
    # link exists, check that it points to the right location
    link_target="$(readlink $HOME/$i)"
    if [ "$link_target" != "$checkout_dir/${links[$i]}" ]
    then
      # wrong location, so remove that
      rm "$HOME/$i"
      echo -n " (changed)"
    else
      # location is right, all good, skip it
      echo -e " [${COLOR_FG_YELLOW}skip${COLOR_RESET}]"
      continue
    fi
  elif [ -e "$HOME/$i" ]
  then
    # file exists, rename it
    mv "$HOME/$i" "$HOME/$i-old"
    echo -ne " ${COLOR_FG_BOLD_BLUE}(exists, rename to '$HOME/$i-old')${COLOR_RESET}"
  else
    # no symlink, no file
    echo -n " (create)"
  fi
  # make the link
  ln -s "$checkout_dir/${links[$i]}" "$HOME/$i"
  echo -e " [${COLOR_FG_GREEN}OK${COLOR_RESET}]"
done
