#!/usr/bin/env bash

# wrapper for meeting-setup script, so I can use a key combo for this
# TODO: set this up as a keyboard shortcut - M

# check if iterm2 is running - if not, we need to start it
pgrep -a iTerm2
if [ "$?" -eq 0 ]
then
  # iTerm2 alread running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

osascript <<EOF
tell application "System Events"
  keystroke "meeting-setup; exit" & return
end tell
EOF
