#!/usr/bin/env bash

# wrapper for meeting-setup script, so I can use a key combo for this

# check if iterm2 is running - if not, we need to start it
if pgrep -a iTerm2
then
  # iTerm2 already running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

osascript <<EOF
tell application "System Events"
  keystroke "meeting-setup; exit" & return
end tell
EOF
