#!/usr/bin/env bash
# Opens new iTerm2 window

# check if iterm2 is running - if not, we need to start it
pgrep -a iTerm2
if [ "$?" -eq 0 ]
then
  # iTerm2 alread running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi
