#!/usr/bin/env bash
# Opens new iTerm2 window

# to set this up to run as hotkey Ctrl-⌥ -⌘ -T (Control-Option-Command-T)
# (instructions adapted from https://apple.stackexchange.com/a/276839)
#
# 1. Create a service using Automator
#
# Launch Automator (hit ⌘ -Space and use spotlight)
# File > New
# Select "Quick Action" and click "Choose"
# In the top right hand of the window:
#   set dropdowns so that 'Service recieves "no input" in "any application"'
# In the second column containing the long list, double-click "Run Shell Script"
#   (this adds the Run Shell Script window on the right)
# Select "/bin/sh" in the "Shell" drop-down
#   (so the shebang at the top of this file will use the correct bash)
# Paste "$HOME/dotfiles/scripts/new-terminal" in the text box
#   (the path to this script file)
# In the top right, click the "Run" button and make sure this works as expected
# File > Save...
#   save this as "NewITermWindow"
#
# 2. Create the hotkey shortcut
#
# System Preferences > Keyboard > Shortcuts
# Select "Services" in the sidebar
# Find "NewITermWindow" under "General"
# Click on the service name
# Click "Add Shortcut"
# type "Ctrl-⌥ -⌘ -T" (Control-Option-Command-T) to assign that shortcut
#
# 3. Allow this shortcut to run from anywhere
#   (should only have to set this up for the first Automator script)
#
# System Preferences > Security & Privacy > Privacy
# click the padlock in the lower left to allow changes
# Select "Accessibility" in the sidebar
# Click on the + sign
# Add Automator
# Add Finder (navigate to /System/Library/CoreServices/Finder)
# click the padlock to close it
# Exit System Preferences
#
# Now you should be able to run this keyboard shortcut from anywhere

# check if iterm2 is running - if not, we need to start it
pgrep -a iTerm2
if [ "$?" -eq 0 ]
then
  # iTerm2 alread running - open a new window
  osascript -e 'tell application "iTerm" to create window with default profile'
else
  # iTerm2 not running - have to start it
  osascript -e 'tell application "Iterm" to activate'
fi

