#!/usr/bin/env bash
# opens new Firefox window

# to set this up to run as hotkey Ctrl-⌥ -⌘ -F (Control-Option-Command-F)
# (instructions adapted from https://apple.stackexchange.com/a/276839)
#
# 1. Create a service using Automator
#
# Launch Automator (hit ⌘ -Space and use spotlight)
# File > New
# Select "Service" and click "Choose"
# In the top right hand of the window:
#   set dropdowns so that 'Service recieves "no input" in "any application"'
# In the second column containing the long list, double-click "Run Shell Script"
#   (this adds the Run Shell Script window on the right)
# Select "/bin/sh" in the "Shell" drop-down
#   (so the shebang at the top of this file will use the correct bash)
# Paste "$HOME/dotfiles/scripts/new_firefox" in the text box
#   (the path to this script file)
# In the top right, click the "Run" button and make sure this works as expected
# File > Save...
#   save this as "NewFirefoxWindow"
#
# 2. Create the hotkey shortcut
#
# System Preferences > Keyboard > Shortcuts
# Select "Services" in the sidebar
# Find "NewFirefoxWindow" under "General"
# Click on the service name
# Click "Add Shortcut"
# type "Ctrl-⌥ -⌘ -F" (Control-Option-Command-F) to assign that shortcut
#
# 3. Allow this shortcut to run from anywhere
#   (should only have to set this up for the first Automator script)
#
# System Preferences > Security & Privacy > Privacy
# click the padlock in the lower left to allow changes
# Select "Accessibility" in the sidebar
# Click on the + sign
# Add Automator
# Add Finder (navigate to /System/Library/CoreServices/Finder)
# click the padlock to close it
# Exit System Preferences
#
# Now you should be able to run this keyboard shortcut from anywhere


# open a new Firefox window (and bring it to the front with focus)
# (I'm running nightly version)
osascript -e 'tell application "FirefoxNightly" to activate'
osascript -e 'tell application "System Events" to keystroke "n" using command down'

