#!/usr/bin/env bash
# Open the oncall info pages in the browser

# backlog grooming
open 'https://docs.google.com/document/d/1FCXglaAH7DFS7NGQGcD9q6XyaBySRlxWIREwUIp90TM/edit'

# oncall logs
open 'https://docs.google.com/document/d/1-r-ZEMDNTtJgpbLExl2JC69ErBfxNI6JhjaHVnIg6ac/edit'

# oncall runbook
open 'https://docs.google.com/document/d/1wHlGDt6-I6BmU0uc520GhShPSVxZnwqV0FOC68nK9OI/edit'

# FI-Web backlog
open 'https://jira01.corp.linkedin.com:8443/secure/Dashboard.jspa?selectPageId=38130'

# weekly email summary template
open 'https://docs.google.com/document/d/17syn-SRRZjnig5tymhfYRDf3WoqFrANYXaGwXCB2-58/edit'

# another playbook (will be migrated to main docs)
open 'https://pages.linkedin.githubprivate.com/multiproduct/voyager-docs/pillars/infra/web/playbooks/oncall'
