#!/usr/bin/env bash
# Automate pasting a password into the terminal

# use this like so:
#  ( sleep 2; paste-term-password "$passwd" ) &
#  sudo make-sandwich

# Arguments
password="$1"

# if nothing passed in, just exit
[ -z "$password" ] && exit

# make sure iTerm2 is in the foreground for this
osascript -e 'tell application "Iterm" to activate'

# and give it a little time before copy-paste
sleep 1;

# backspace a few times to clear out anything in stdin
# then keystroke the password
# then clear the clipboard
osascript <<EOF
set the clipboard to "$password"
tell application "System Events"
  key code 51
  delay 0.1
end tell
tell application "System Events"
  key code 51
  delay 0.1
end tell
tell application "System Events"
  key code 51
  delay 0.1
end tell
tell application "System Events"
  repeat with char in the characters of (the clipboard)
    keystroke char
  end repeat
  delay 0.1
  keystroke return
end tell
set the clipboard to ""
EOF
