#!/usr/bin/env bash
# Paste a red X ❌

# initial delay to this doesn't capture the keyboard shortcut chars
sleep 0.5

# use the clipboard
# TODO: save and restore the clipboard contents?
osascript <<EOF
set the clipboard to "❌"
tell application "System Events" to keystroke "v" using command down
EOF
