#!/usr/bin/env bash
# Paste the link to my Zoom meeting

# Read this from a local file on disk, so I'm not committing the link to a public repo ;)
zoom_file="$HOME/zoom-link.txt"

# show a dialog if there is an error, since this is used as a keyboard shortcut
show-dialog() {
  message="$1"

  osascript<<EOSCRIPT
set theDialogText to "$message\n\n\n"
display dialog theDialogText buttons {"I should fix that..."} default button "I should fix that..."
EOSCRIPT
}

# do the thing

if [ ! -f "$zoom_file" ]
then
  show-dialog "File '$HOME/zoom-link.txt' not found"
  exit
fi

zoom_link="$(<$HOME/zoom-link.txt)"

if [ -z "$zoom_link" ]
then
  show-dialog "File '$HOME/zoom-link.txt' is empty"
  exit
fi

# this doesn't work
#osascript -e "tell application 'System Events' to keystroke '$zoom_link'"

# but using the clipboard does
osascript <<EOF
set the clipboard to "$zoom_link"
tell application "System Events" to keystroke "v" using command down
EOF
